# Generated by Django 5.2.9 on 2026-02-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(blank=True, choices=[('tech', 'Tech'), ('lifestyle', 'Lifestyle'), ('education', 'Education'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
